apiVersion: v1
kind: Service
metadata:
  name: webrtc
spec:
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: webrtc
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: webrtc
  name: webrtc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webrtc
  template:
    metadata:
      labels:
        app: webrtc
    spec:
      containers:
      - image: asia.gcr.io/sixth-legend-250111/webrtc:latest
        imagePullPolicy: Always
        name: webrtc
